server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: health-data-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/fitty-health}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        max.block.ms: ${SPRING_KAFKA_PRODUCER_MAX_BLOCK_MS:1000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
