apiVersion: v1
kind: Service
metadata:
  name: health-data-service
  namespace: fitty-app
spec:
  selector:
    app: health-data-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-data-service
  namespace: fitty-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-data-service
  template:
    metadata:
      labels:
        app: health-data-service
    spec:
      containers:
        - name: health-data-service
          image: fitty-cp-01:5000/fitty/health-data-service:local
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: SERVER_PORT
              value: "8083"
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://fitty:fitty@mongo.fitty-data.svc.cluster.local:27017/fitty-health?authSource=admin
          envFrom:
            - configMapRef:
                name: fitty-app-config
          resources:
            requests:
              cpu: 200m
              memory: 384Mi
            limits:
              cpu: 750m
              memory: 768Mi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
