spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    inetutils:
      ignored-interfaces:
        - VirtualBox*
      timeout-seconds: 10
    config:
      server:
        native:
          search-locations: classpath:/configurations
server:
  port: 8888
logging:
  level:
    org.springframework.cloud.commons.util.InetUtils: info